name: es-check-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: ali-kamalizade/es-check-action@1.0.2
        with:
          directory: "dist"
          ecmaVersion: "es5"
          files: "*.js"
